### PR TITLE
Adding support for FICO Xpress to CVXPY

### PR DESCRIPTION
**Pull request by merraksh**
The FICO Xpress optimizer can solve linear, conic, and quadratic optimization problems with possibly integer or binary variables. This PR is to add support for the Xpress solver. The solver can be used via a Python module called xpress that can be installed via PyPI or conda.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
This is a great contribution! Be sure to rebase correctly on master, so the only changes are the solver file you're adding and the other places you need to register it.

**Comment by merraksh** [comment]
@SteveDiamond I'm not sure what happened. I tried rebasing on upstream/master and ended up with a few hours of work. I did have a path with only Xpress-related changes, but had to merge after a git pull and ended up with a non-clean rebase.

**Comment by merraksh** [comment]
Commit 8d0aa4d4 tries to undo all non-Xpress changes from the pull request, as I must have made a mistake while rebasing. Resetting to it results in only one failed test (the one that depends on the xpress module, not cvxpy).

**Comment by SteveDiamond** [comment]
Ok, maybe just start a new branch, forked from master, and manually copy over the xpress interface and change the relevant files? Shouldn't be too many.

**Comment by SteveDiamond** [comment]
Also did you see test_conic_solvers.py and test_qp_solvers.py?

**Comment by merraksh** [comment]
@SteveDiamond I created a new branch with only the relevant changes. We can decline/close/delete this PR and I'll submit a new one from that branch if this is OK.

The only failure that's left is the spurious output lines in test_verbose() in test_problem.py, which will be fixed with the next release of the Xpress Python module.

What about test_qp_solvers and test_conic_solvers?

**Comment by SteveDiamond** [comment]
Ok I'll close this. You do need to add tests to test_conic_solvers and test_qp_solvers. Here's info about how to do it: https://www.cvxpy.org/contributing/index.html#solver-interfaces

**Pull request closed without merging**
