### PR TITLE
Resolve existing CI issues, new wheels for OSX, improvements for Windows wheels

### LINKED ISSUE #738: Update Travis environment PYPI_SERVER
CVXPY version 1.0.24 was recently uploaded to PyPi. This release includes a Windows wheel and egg. However, unlike previous releases, it does not include a source archive for installation on Mac OS X and Linux. See https://pypi.org/project/cvxpy/1.0.24/#files

Here's the latest Travis build: https://travis-ci.org/cvxgrp/cvxpy/builds/539866720

I'm not too familiar with deployment, so I'm not sure what the issue is. The 2.7 builds failed, but the MAC OS X and Linux builds with DEPLOY_PYPI="true" succeeded.

@rileyjmurray @SteveDiamond , any ideas what might be happening?

### PR DESCRIPTION
**Pull request by rileyjmurray**
This PR resolves #738, and adds new CI functionality. In order for this PR to work, Travis and AppVeyor will need new environment variables ``PYPI_API_ENDPOINT=https://pypi.org/pypi`` (note the lack of a final forward slash in that URL).

By using conda's "pinned" dependencies, this PR builds wheels for 
 * Windows: Python 3.6 and 3.7,
 * OSX: Python 2.7, 3.6, and 3.7.

The wheels for OSX are entirely new. The Python 3.7 wheel for Windows is new.

I attempted to have wheels build for python 3.5 on Windows and OSX. This failed because of a (somewhat obscure?) packaged called ``readme_renderer``, which seems to be required for uploading wheels to PyPI. Using the conda channels we currently have, there is no appropriate version of ``readme_renderer`` which exists for Python 3.5. In the next major improvements to CI testing, I will move away from ``conda install ...`` for managing packages, and instead work with pip. Hopefully that will allow us to build python 3.5 wheels.

### CODE REVIEW

**Comment by rileyjmurray** [comment]
Pinging @akshayka , @SteveDiamond

**Comment by akshayka** [comment]
This is great! LGTM.

**Comment by akshayka** [comment]
@SteveDiamond, this should be ready to merge once the Travis and AppVeyor have the environment variables `PYPI_API_ENDPOINT=https://pypi.org/pypi` (note the lack of a final forward slash in that URL).

**Comment by SteveDiamond** [comment]
I added the variable. Thanks for doing this!

**Pull request merged**
