### PR TITLE
Fixed OSQP interface

### PR DESCRIPTION
**Pull request by gbanjac**
Fixes https://github.com/cvxgrp/cvxpy/issues/620

### CODE REVIEW

**Comment by rileyjmurray** [comment]
The Travis builds seem to be failing with a nontrivial error. @gbanjac can you take a look at those?

**Comment by gbanjac** [comment]
The error seems to be related to the OSQP `update` function. I will take a look at it.

**Comment by gbanjac** [comment]
@rileyjmurray All the unit tests are passing now. However, there is still a problem with `flake8`, which is not related to this PR though.

**Comment by SteveDiamond** [comment]
Thanks! I'll look into the flake8 issue.

**Pull request merged**
