### PR TITLE
this should fix issue with early deletion of mosek Task objects

### PR DESCRIPTION
**Pull request by rileyjmurray**
Changes should resolve issues in #500 and #497 . I have tested with mosek 8 and 9, with both nosetests and running `cvxpy/examples/tsp_mip.py`.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Hi Riley, what is the current plan for this PR? It's not the end of the world if we need to put out a simple patch to fix the Mosek issue and deal with other challenges later.

**Comment by rileyjmurray** [comment]
I'm working on it today. Goal is to get automated pypi deployment to work (but to do this only when the version number updates).

**Comment by rileyjmurray** [comment]
Should be ready to merge. As long as appropriate environment variables are set in the Travis CI website, a single commit that bumps version should result in automatic deployment to anaconda and pypi (for mac and linux).

**Comment by SteveDiamond** [comment]
Awesome!

**Pull request merged**
