### PR TITLE
Basis identification and basic solution retrieval from MOSEK

### PR DESCRIPTION
**Pull request by aszekMosek**
The bfs kwarg for MOSEK was not documented.

### CODE REVIEW

**Comment by aszekMosek** [comment]
By the way for linear problems: The basis identification time in MOSEK is wasted time if CVXPY by default retrieves only the interior point solution. A sensible solution would be to disable basis identification if bfs=False.

I will be happy to expand this PR if you think it makes sense.

**Comment by SteveDiamond** [comment]
Yes, please add the proposed PR. I wasn't aware that the basis identification was being computed.

**Comment by akshayka** [comment]
@rileyjmurray , since you have familiarity with the MOSEK interface, would you like to review this change?

**Comment by rileyjmurray** [comment]
I'll review (and merge, as appropriate) in the next couple days.

**Comment by rileyjmurray** [comment]
It occured to me that @aszekMosek couldn't have run the new test suite (from #910) before submitting this PR. After running local tests on my machine, I can confirm that MOSEK passes the now-standard test-suite from #910.

**Pull request merged**
