### PR TITLE
Lazily reduce problem data tensor

### PR DESCRIPTION
**Pull request by akshayka**
Reduce problem data tensor on first call to apply parameters.

An intermediate `ParamConeProg` is constructed when canonicalizing cone
programs; this `ParamConeProg` is never actually evaluated, so reducing
its tensor is unnecessary.

@sbarratt

### CODE REVIEW

**Review by SteveDiamond — APPROVED** [review]
LGTM

**Comment by akshayka** [comment]
@SteveDiamond @sbarratt The derivative tests are failing with


  File "C:\conda\envs\testenv\lib\site-packages\ecos.py", line 62, in solve
1898    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
1899TypeError: 'eps' is an invalid keyword argument for this function


This appears to be related to the recent release of diffcp, which included ECOS. Could one of you look into it?

**Comment by sbarratt** [comment]
Ah, whoops, looks like eps is no longer a valid argument if the solver is
"ECOS".

Shane

**Comment by SteveDiamond** [comment]
Not sure what to do here. We have a naming clash with the ``solver`` keyword. It's used in cvxpy and in diffcp.

**Comment by akshayka** [comment]
> Not sure what to do here. We have a naming clash with the `solver` keyword. It's used in cvxpy and in diffcp.

That's unfortunate.

I guess we can't really change CVXPY's interface. Can we change the keyword argument name in `diffcp` to `method`, instead of `solver`?

**Comment by akshayka** [comment]
> > Not sure what to do here. We have a naming clash with the `solver` keyword. It's used in cvxpy and in diffcp.
> 
> That's unfortunate.
> 
> I guess we can't really change CVXPY's interface. Can we change the keyword argument name in `diffcp` to `method`, instead of `solver`?

er or I guess `solve_method`, since CVXPY also uses `method`

**Comment by akshayka** [comment]
Rebased on top of b8a54937311063db42ac9a49e8ddce5520920b42 to retrigger the build ...

**Pull request merged**
