### PR TITLE
add axis parameter to log_sum_exp atom

### PR DESCRIPTION
**Pull request by mwytock**
Hi Steven,

Small change here - CVXOPT seems to throw an error once in awhile?

Cheers,
Matt

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Unfortunately I can't merge this if Travis fails. CVXOPT does sometimes fail for unclear reasons. Could you investigate CVXOPT's failure a bit more and post it as an issue?

If we can't fix CVXOPT, you can change the test by adding (lambda expression, CVXOPT) to the list of KNOWN_SOLVER_ERRORS. You'll have to change the code a little bit because right now the known solver errors matches on atoms.

**Comment by mwytock** [comment]
how to investigate? sometimes it fails, sometimes it passes...

**Comment by mwytock** [comment]
Created issue https://github.com/cvxgrp/cvxpy/issues/249

**Comment by mwytock** [comment]
green

**Comment by SteveDiamond** [comment]
Looks good! Thanks for doing this.

**Comment by SteveDiamond** [comment]
Sorry I thought I had merged this a long time ago.

**Pull request merged**
