### PR TITLE
lazy import numpy for header injection

### PR DESCRIPTION
**Pull request by shariat**
This is not still enough, since `scs` and `ecos` have the same problem. Also used `find_packages` instead of listing all the packages manually.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
This is interesting, but all the CI tests failed on Travis.

**Comment by shariat** [comment]
doesn't seem to be related to this change, is `cvxpy` tested with `numpy==1.15.0` ?

**Comment by shariat** [comment]
numpy version was fixed to 1.13 in travis.

**Comment by rileyjmurray** [comment]
@shariat , just for my education, can you explain this PR? Specifically, what is meant by "lazy import [X] for header injection", and what are the changes made to setup.py?

Also, if this is ready for merging you should probably re-ping Steven and let him know.

**Comment by shariat** [comment]
ping @SteveDiamond

**Comment by shariat** [comment]
@rileyjmurray the goal is to run `setup.py` without the need for `numpy` being already installed.

**Comment by rileyjmurray** [comment]
@SteveDiamond it looks like this is ready, from what I can tell.

**Comment by SteveDiamond** [comment]
Yeah, looks good!

**Pull request merged**
