### PR TITLE
a test for cvxcore overflows (and other minor changes)

### PR DESCRIPTION
**Pull request by rileyjmurray**
@SteveDiamond following our slack thread, here's a PR containing a test to cause a cvxcore overflow error. I created a new file within ``cvxpy/tests`` which won't be discovered by automatic testing suites. The intention is that we execute that file with command line arguments only when necessary. The current file contains a test which takes about 100GB RAM; the overflow happens in Eigen. To see what's going on in Eigen you're going to need to execute the python test script within GDB, and make sure cvxcore was built without GCC compiler optimizations (change line 50 of setup.py to use flag ``"-O0"``).

[One of these commits](https://github.com/cvxgrp/cvxpy/commit/2698c33f2641a53e75c8cc274d1c416a777ae665) modified ``cvxpy/cvxcore/src/ProblemData.hpp``. Our normal test suite passed after those changes, and those changes did seem to address the ``int`` vs ``long`` issue in ``getI``, ``getJ``, ``getV`` from #826. However, the changes didn't actually help with the Eigen error mentioned above. Since I'd rather not mess with cvxcore without good reason, I rolled those changes back.

Other changes:
 *  ``test_curvature.py`` to resolve deprecation warnings.
 * CPLEX tests, in keeping with #920.
 * an incorrect docstring regarding the exponential cone.

### CODE REVIEW

**Comment by akshayka** [comment]
Riley, just to make sure I understand: do you mean that commit 2698c33f2641a53e75c8cc274d1c416a777ae665 fixed the overflow in `getI`, etc., but exposed another bug, in Eigen? If that's the case, I think that commit should get merged in. There's no harm in accepting longs instead of ints.

Additionally, if you have the error message  / stack trace / debug output describing the overflow in Eigen, can you paste it here? (Or maybe it's in a related issue, which I haven't seen?)

**Comment by rileyjmurray** [comment]
@akshayka that commit *might have fixed* (perhaps "probably fixed") the overflow in ``getI``, etc...

I use the qualifications there, because the test case provided in this commit never triggered overflow in the same way as #826. The Eigen error I mention occurs both with and without the change in commit 2698c33f2641a53e75c8cc274d1c416a777ae665. 

I guess I was thinking that if I don't know that a change to cvxcore demonstrably fixes something specific, then I shouldn't make that change. But at the same time- local tests did pass with the change in 2698c33f2641a53e75c8cc274d1c416a777ae665. If you think the change is simple and natural enough, then I can add it back to this PR. Just give the word if so.

**Comment by rileyjmurray** [comment]
I'll also post the stacktrace here later today.

**Comment by SteveDiamond** [comment]
@rileyjmurray the commit is a good start! Sadly the functions that interface between cvxcore and cvxpy are pretty hard to change. For example, if you change a function like getI you need to regenerate the swig interface, and there may be more to it as well, like changing cvxcore.i. This is something we can work on together.

**Comment by SteveDiamond** [comment]
@rileyjmurray why don't you merge this? The small changes are nice.

**Pull request merged**
