### PR TITLE
handle builtin when it is a dict

### LINKED ISSUE #594: 1.0.9 fails setup.py when installing over pip (__NUMPY_SETUP__ attribute)
The newest built could not be installed correctly over pip.
The new numpy header injection method seems problematic.(?)

`AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'`
Detailed log on travis at the installation step can be found [here](https://travis-ci.org/lpfann/fri/jobs/437299138).

### PR DESCRIPTION
**Pull request by shariat**
closes #594.
`__builtins__` can be a dict. see https://docs.python.org/2/reference/executionmodel.html

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Can you explain what happened in #594? Why it's a dict?

**Comment by akshayka** [comment]
@SteveDiamond apparently whether or not .__builtin__ is a dict depends on particular Python implementation. From the linked documentation:

> CPython implementation detail: Most modules have the name __builtins__ (note the 's') made available as part of their globals. The value of __builtins__ is normally either this module or the value of this modules’s __dict__ attribute. Since this is an implementation detail, it may not be used by alternate implementations of Python.

**Comment by bstellato** [comment]
Looks like a problem with the GLPK optimizer precision: https://travis-ci.org/cvxgrp/cvxpy/jobs/441951455#L3487.

**Comment by SteveDiamond** [comment]
ok, I'll change the tolerance.

**Pull request merged**
