### PR TITLE
MOSEK SDP interface - initial working prototype (testing needed)

### PR DESCRIPTION
**Pull request by enzobusseti**
I have a working implementation - Steven is there any code to test it against CVXOPT and SCS?

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Fantastic! Thanks so much for doing this. I'm going to use it immediately. 

You mean test it as in performance tests? There aren't any performance tests right now.

**Comment by SteveDiamond** [comment]
Ok, I shouldn't have merged that. Add these lines to ``test_constant_atoms.py``:
```
# Test MOSEK if installed.
if MOSEK in installed_solvers():
    SOLVERS_TO_TRY.append(MOSEK)
    SOLVER_TO_TOL[MOSEK] = 1e-6
```
right after the same lines for Elemental.

**Comment by SteveDiamond** [comment]
Sorry, I screwed that up. I guess you need to open a new pull request. Also you forgot to include changes to ``semidefinite.py``.

**Comment by enzobusseti** [comment]
Ooops yeah. Let me work on this another little bit. Right now I’m not sure it is doing the right thing..

**Pull request merged**
