### PR TITLE
Add the Xpress Optimizer to CVXPy

### PR DESCRIPTION
**Pull request by merraksh**
Allow for solving linear, conic, and quadratic optimization problems, with or without discrete variables, with the FICO Xpress Optimizer. The Xpress problem class also allows for retrieving Irreducible Infeasible Subsystems (IISs) in the event that the problem is infeasible.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Looks really good on the whole! I have some comments/questions. Remember to check your code style with flake8.

**Comment by SteveDiamond** [comment]
Thanks for making it flake8 compliant! I'm happy to merge as soon as you get it passing travis-CI. looks like it breaks now because you import xpress in the wrong place.

**Comment by SteveDiamond** [comment]
Looks good! Thanks!

**Comment by merraksh** [comment]
Great! Thanks.

**Comment by SteveDiamond** [comment]
I'm adding an Xpress interface to the very soon to be released 1.0 branch. I'm trying to get a license to test it but you guys could test it/fix it if you like.

**Comment by merraksh** [comment]
After downloading the 1.0 branch and setup, a python setup.py install seems
to run fine, but then upon import cvxpy this is what happens:

  File "/home/pietro/code/cvxpy-1.0/cvxpy/CVXcanon/python/CVXcanon.py",
line 247, in LinOp
    __swig_setmethods__["data_ndim"] = _CVXcanon.LinOp_data_ndim_set
AttributeError: 'module' object has no attribute 'LinOp_data_ndim_set'

On cvxpy 0.4.11, import cvxpy works fine.

**Comment by rw** [comment]
I second the bug report by @merraksh .

**Comment by rw** [comment]
Here's a solution: install CVXcanon via git.

```
pip3 install --no-use-wheel --verbose -e git+https://github.com/cvxgrp/CVXcanon.git#egg=cvxcanon
```

**Comment by SteveDiamond** [comment]
Hi guys, I did a major clean up of CVXPY which included migrating all the pre-1.0 style solver interfaces to 1.0 style interfaces, in order to remove lots of deprecated code. I was not able to install the XPRESS solver so I couldn't test the new XPRESS interface. If you're still interested and able to test it (or help with installing XPRESS), I'd really appreciate. I had to simplify the interface in order to fit it into the new format.

**Comment by merraksh** [comment]
Hi Steven,

 

really sorry about the late reply (ten months!). We are interested in CVXPY working with Xpress and we'd be more than happy to help you installing Xpress and/or test the interface. For starters, installing the Xpress interface should be just a matter of "pip install xpress" or "conda install -c fico-xpress xpress". In any event, feel free to ping me for help on install/use of the Xpress Python interface. I forked cvxpy and was looking through the *_conif.py file. What are the main changes?

 

Thanks,

Pietro
 

Sent: Wednesday, March 13, 2019 at 10:46 PM

**Comment by rileyjmurray** [comment]
Pinging @merraksh , to make sure you see #923.

**Comment by merraksh** [comment]
Saw it, thanks.

**Pull request merged**
