### PR TITLE
Fix a problem of p[k]

### PR DESCRIPTION
**Pull request by yzy1996**
The code of line 70 missed a [k]

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Thanks!

**Comment by yzy1996** [comment]
And I want to know when will [cvxpy website](https://www.cvxpy.org/examples/dgp/power_control.html) be updated? Thank you!

**Comment by SteveDiamond** [comment]
Done.

**Comment by yzy1996** [comment]
Yeah, really appreciated!

**Pull request merged**
