### PR TITLE
example: consensus ADMM: add missing variables

### PR DESCRIPTION
**Pull request by dplarson**
The consensus ADMM example was missing two variables: gamma (for
weighting the L_1 norm) and NUM_PROCS (the number of threads of the
multiprocessing pool).

Related: since I've noticed multiple examples with similar issues (i.e. missing problem variables), would the maintainers prefer a bulk PR that attempts to update all the example scripts? Or one PR per example?

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Good catch! Thanks!

**Comment by dplarson** [comment]
@SteveDiamond Since there appear to be similar issues (i.e. missing variables) in other examples, would you prefer a single PR that fixes all the issues or one PR per example?

**Comment by SteveDiamond** [comment]
A single PR would be best. Thanks for fixing these mistakes!

**Comment by dplarson** [comment]
Happy to help!

**Pull request merged**
