### PR TITLE
Adding reciprocal product as a new convex atom

### PR DESCRIPTION
**Pull request by angeris**
Adding in the (somewhat surprising!) new atom `inv_prod` equal to

```
(Π x)⁻¹
```

for some vector `x`, as per @akshayka 's recommendation.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Should we add documentation?

**Comment by angeris** [comment]
Now that would be a good idea! Will do later today :)

**Comment by rileyjmurray** [comment]
Pinging @angeris, will you be able to write documentation any time soon?

**Comment by angeris** [comment]
Gah! Apologies, this totally slipped my mind! Yes, will do by tomorrow

**Comment by angeris** [comment]
On the documentation: it is just including the atom in `functions/index.rst` and...? Anywhere else?

**Comment by angeris** [comment]
Ok, documentation is done. Not sure why the new commits are not showing up on the PR, but so it goes.

**Comment by SteveDiamond** [comment]
Ok thanks! Merging in.

**Pull request merged**
