### PR TITLE
Adding NAG interface for v1.1.a1

### PR DESCRIPTION
**Pull request by shuanghuabai**
This is to add modified NAG interface due to changes in v1.1.a1, src, doc and tests have all been modified.  Thanks a lot, Shuanghua.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Thanks @shuanghuabai ! Sorry you had to do so much work on this. As I mentioned, I tried to update the interface myself but wasn't able. I ran the PR locally and test_nag_socp_1 and test_nag_lp_4 are still failing for me. Do they work on your machine?

**Comment by shuanghuabai** [comment]
No problem at all. All tests passed on my machine. Please if you could update your NAG Library to 27.0.2.0, they should all work. Thanks a lot @SteveDiamond.

**Comment by SteveDiamond** [comment]
It works now, thanks!

**Comment by shuanghuabai** [comment]
Thank you very much.

**Pull request merged**
