### PR TITLE
Allow kron to have Variable in first argument

### PR DESCRIPTION
**Pull request by rileyjmurray**
This is a definitive resolution to #457 (native cvxpy implementation, as opposed to numpy-backed implementation).

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Is this finished? You'll need to implement a new LinOp for kronecker products with the first argument as a variable, won't you? That's why I haven't done it.

**Comment by rileyjmurray** [comment]
From the atom-level tests I conducted, things worked fine without implementing a new LinOp. I will write some systems-level tests and get back to you.

**Comment by rileyjmurray** [comment]
@SteveDiamond your intuition was correct. The simple changes I made allow Variables in the first argument in that the following code behaves as expected
```
a = np.random.randn(3,3)
b = np.random.randn(3,3)
x = cvxpy.Variable((3,3))
expr = cvxpy.kron(x, a)
x.value = b
np.allclose( expr.value, np.kron(b, a) )
```
However, the changes I made do not pass system-level tests in that canonicalization fails when passing to a solver.

**Comment by rileyjmurray** [comment]
Closing this PR until I am more familiar with LinOps.

**Pull request closed without merging**
