### PR TITLE
Update continuous integration scripts (mostly deployment related)

### PR DESCRIPTION
**Pull request by rileyjmurray**
This PR contains changes to how we use continuous integration services (TravisCI and AppVeyor). There are three types of changes here:
1. Simple reorganization of CI files (to improve readability / maintainability).
2. Correction of an error in meta.yaml, which caused conda builds to fail after [this commit](https://github.com/cvxgrp/cvxpy/commit/b42d5382a3e86047ad9fc0958fa2fb063520316a#diff-ca1ae5e1c32bb3b74558c6766de4f0c2).
3. New deployment features.

The new deployment features are as follows:
 - Windows wheels are uploaded to pypi. These work 100%.
 - Windows builds are pushed to Anaconda. These install correctly, but contain a poorly linked version of SCS, which does not have support for semidefinite constraints of order > 2. As a result, a Windows user can run ``conda install cvxpy`` and get to most up-to-date version of cvxpy, but they will need to separately install SCS (``pip install scs<=2.0``) in order to run tests. From extensive discussion in #627, there is no way around this poorly functioning Windows build without someone updating an SCS conda package.

Separately, I'll note that we are not far off from pushing "manylinux" wheels. However that will require changes to how the Travis "deploy_script.sh" is setup, and I'd like to make those changes in a separate PR.

In order to properly merge this PR, I need @SteveDiamond to setup the following environment variables from the TravisCI and AppVeyor websites, with their personal accounts (most of these should already be defined, at least for TravisCI):
 - CONDA_UPLOAD_TOKEN
 - CONDA_USER
 - PYPI_USER
 - PYPI_PASSWORD
 - PYPI_SERVER

The last of the above environment variables should be ``PYPI_SERVER=https://upload.pypi.org/legacy/``. If a cvxpy contributor needs to test deployments themselves (i.e. using their own fork of cvxpy), then they also need to set the above environment variables. However, they should set ``PYPI_SERVER= https://test.pypi.org/legacy/``. It may be good to update [CONTRIBUTING.md](https://github.com/cvxgrp/cvxpy/blob/master/CONTRIBUTING.md) to include a section on how to help with deployment and CI related issues. Such a section should (at the very least) mention the need to use the appropriate value for ``PYPI_SERVER``.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Sorry for the slow reply! I was out of town. This all looks great! I added the environment variables you mentioned to Travis and Appveyor.

**Comment by akshayka** [comment]
@SteveDiamond Is this ready to be merged?

@rileyjmurray , adding a deployment/CI section to our contributing guide is an excellent idea! Would you (or Steven) like to write a first draft, whenever you have time? I'm actually not very familiar with our CI process, so I'm looking forward to reading the draft to get myself up-to-speed :)

**Comment by SteveDiamond** [comment]
@akshayka I believe it's ready to be merged. @rileyjmurray is that right? I've set the environment variables.

**Comment by rileyjmurray** [comment]
It is indeed ready to be merged.

@akshayka I'll update the CI-related contributing guidelines in my next PR (which will be focused on adding deployment of manylinux wheels to pypi).

**Comment by akshayka** [comment]
Merged, but the Python 2.7 travis tests are failing: https://travis-ci.org/cvxgrp/cvxpy/jobs/539536434

**Comment by akshayka** [comment]
@rileyjmurray , do you know what might be wrong with the 2.7 Travis builds?

**Comment by rileyjmurray** [comment]
The error messages are pretty awful, so I cannot say for sure. This only happens in the deployment step (install and tests succeed). There seems to be a difference where conda-build is using numpy 1.16 and scipy 1.2 (although the install and tests are with numpy 1.14 and scipy 1.1). The higher versions of these packages during conda-build may have inherent issues with python 2.7. If nothing else, the conda-recipe should be changed to have the same package version requirements as in setup.py.

**Comment by akshayka** [comment]
> If nothing else, the conda-recipe should be changed to have the same package version requirements as in setup.py.

Interesting -- I can try to fix this ...

I'm unsure why the source deployment to PyPi failed at master, the builds with DEPLOY_PYPI=True succeeded ... I'll create a separate issue for that.

**Comment by rileyjmurray** [comment]
It would be helpful if you looked into it a bit. I can take a look later this next week but I’m pretty slammed for the next few days.

**Pull request merged**
