### PR TITLE
fixed way SDP constraints were enforced in MOSEK + test

### PR DESCRIPTION
**Pull request by enzobusseti**
The nosetest fails on one test. I tried to replicate it but can't find where in the tests it is. Can you give me the code that generates the error? I'll figure out what's wrong.

I have preliminary performance tests :)
10x10 SDP 
  MOSEK 300ms
  CVXOPT 2sec
20x20 SDP
  MOSEK 2sec
  CVXOPT 40sec

### CODE REVIEW

**Comment by SteveDiamond** [comment]
The test is failing because of a "NEAR_OPTIMAL" status. It's this problem
```
from cvxpy import *
X = Variable(3,3)
z = Variable(3)
constr = [X == [[1, 0, 0],
                             [0, 1, 0],
                             [0, 0, 1]],
         z == [1, 2, 3]]
prob = Problem(Minimize(matrix_frac(z, X)[0,0]), constr)
prob.solve(solver=MOSEK)
```
but it succeeds when I run it outside of nosetests.

**Comment by enzobusseti** [comment]
I tried to run it, I do get an "optimal_inaccurate" status. Just to be clear, what "optimal_inaccurate" means? I thought it means that the problem is solved but the solver is not sure whether the solution is accurate. If it is a failure status I'll simply output "optimal" whenever I'm outputting "optimal_inaccurate"

**Comment by SteveDiamond** [comment]
optimal inaccurate means the solver solved the problem to a lower accuracy than it normally demands, but still a reasonable accuracy. Keep outputting optimal inaccurate. I'd just change the line
```
if problem.status == OPTIMAL:
```
to
```
if problem.status in [OPTIMAL, OPTIMAL_INACCURATE]:
```

**Comment by enzobusseti** [comment]
Sounds good. You mean in test_constant_atoms?

**Comment by SteveDiamond** [comment]
Yeah, in test_constant_atoms

**Comment by SteveDiamond** [comment]
Everything passes for me! I'm merging it in. Thanks again for doing this!

**Pull request merged**
