### PR TITLE
Default to conic solvers for LPs

### PR DESCRIPTION
**Pull request by akshayka**
QP solvers like OSQP can take many iterations for LPs. For example,
for the l1-regularized SVM example

  https://www.cvxpy.org/examples/machine_learning/svm.html,

OSQP can take > 20,000 iterations to converge (so a solver error is thrown),
whereas an IPM like ECOS is much faster.

### CODE REVIEW

**Comment by bstellato** [comment]
These are actually good examples to try to improve OSQP! 

By the way, also SCS has issues since it returns "Solved/Inaccurate" for most of the problems in the regularization path. I believe it does not throw an error because it does not complain when the maximum number of iterations is reached. 

Adding a small quadratic regularization to the cost function makes both of them converge but it might not be ideal as a general approach.

**Comment by akshayka** [comment]
It’d definitely be interesting to see how to improve OSQP for LPs! Yeah, SCS also struggles, which is why ECOS is our default conic solver.

This PR is totally open for discussion. As you said, using ECOS by default seemed like the easiest way to ensure things worked out-of-the-box, so to speak.

**Comment by rileyjmurray** [comment]
I very much support using ECOS as the default solver for LPs.

**Comment by akshayka** [comment]
@bstellato , @rileyjmurray , thanks for your input! Since we're all in agreement, I'll move forward with this PR.

**Comment by rostyboost** [comment]
FYI, the behavior for Gurobi is the exact opposite unfortunately, because `gurobi_qpif.py` is faster to handshake to Gurobi backend than `gurobi_conif.py`

**Pull request merged**
