### PR TITLE
add pyproject.toml

### PR DESCRIPTION
**Pull request by ali5h**
since `pip 10`, `pyproject.yaml` is supported. It can be used to have `pip`
install `numpy` before running `setup.py`. So we can remove custom `numpy`
injection logic.

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Thanks! What will happen for people with older pip? Can you add a pip version as a requirement?

**Comment by ali5h** [comment]
they will have to install `numpy` first or upgrade `pip`

**Comment by ali5h** [comment]
you cannot add pip min version, same as `setuptools`

**Comment by SteveDiamond** [comment]
@akshayka what do you think? I really appreciate the contribution, and it is cleaner, but I'm hesitant to break the installation for old versions of pip.

**Comment by akshayka** [comment]
Is the NumPy injection a big issue? I suspect most people using CVXPY will already have NumPy installed, whereas many people might not have pip 10, which is only a year old. So the lesser of two evils, at least right now, might be to keep things as is, even if adding a pyproject.toml file is the correct thing to do.

**Comment by ali5h** [comment]
if you `git blame` I added this header injection myself, but later found this better solution. So this was failing already for those who don't have `numpy` installed.

**Comment by akshayka** [comment]
Oh, I wasn't aware of the history of the injection logic --- thanks for your contributions! :)

pip 10 seems like it came out just over a year ago (https://pip.pypa.io/en/stable/news/#id119). I wouldn't be surprised if many folks haven't upgraded yet, but I have no data on this. Have pip 10 / pyproject.toml's been adopted widely / how can we find out if they've been adopted widely?

**Comment by SteveDiamond** [comment]
Could we leave the numpy injection and also have the pyproject.toml file? Maybe that would help with #724.

**Comment by ali5h** [comment]
yes, i think it does help with #724, at least in my local tests

**Comment by SteveDiamond** [comment]
Ok, I added a pyproject.toml. I'll leave the numpy injection as it is in case people don't have pip 10. Thanks for your contribution!

**Pull request closed without merging**
