### PR TITLE
add axis parameter to pnorm(x, 2)

### PR DESCRIPTION
**Pull request by mwytock**
Hi Steven,

This makes it much easier to write sum-of-norms regularization e.g. without unrolling the sum (for example, network lasso paper you dont need |E| terms, http://web.stanford.edu/~hallac/Network_Lasso.pdf)

This is consistent with how linalg.norm() works, although i just added the code for p=2 for now.

Cheers,
Matt

### CODE REVIEW

**Comment by SteveDiamond** [comment]
Looks good to me. I've been meaning to add this for a while. Does it require NumPy 1.10? There was a NumPy error in the Travis tests (which use NumPy 1.9).

At some point we should add a version of ``SOC_Elemwise`` that can take a matrix for ``X`` and an axis argument, so everything is vectorized.

**Comment by mwytock** [comment]
looks like keepdims was added to linalg.norm in 1.10 so i think its needed
(i believe weird things happen if numeric() collapses its return value to a
1D array)

**Comment by mwytock** [comment]
let me know how you want me to resolve this... if 1.9 support is important than i think we could do something manually reshape to the right dimension

**Comment by SteveDiamond** [comment]
1.9 support isn't that important, but this seems like too small a thing to
require 1.10 for. Could you see if there's an easy fix for 1.9?

**Comment by mwytock** [comment]
sure thing, thats fixed now ... fixing one more python 3 bug (i typed xrange for some reason...)

agree re: SOC_Elemwise taking matrix args that would be nice here

**Comment by mwytock** [comment]
fyi - green now :)

**Comment by SteveDiamond** [comment]
Great, merging now.

**Pull request merged**
